baseURL: "https://Leonard-Albuquerque.github.io/LeonardJamesDevBlogHugo/"
languageCode: "pt-br"
title: "Leonard James Development Blog"
theme: "PaperMod"

params:
  env: production

  homeInfoParams:
    Title: "Leonard James"
    Content: >
      Desenvolvedor Full-stack Jr, entusiasta de **Golang** e **TypeScript**.

      Este blog é um espaço para documentar problemas reais
      resolvidos no dia a dia como desenvolvedor.

  socialIcons:
    - name: Github
      url: "https://github.com/Leonard-Albuquerque"
    - name: Rss
      url: "index.xml"

  mainSections:
    - posts
