baseURL: "https://Leonard-Albuquerque.github.io/LeonardJamesDevBlogHugo/"
languageCode: "pt-br"
title: "Leonard James Development Blog"
theme: "PaperMod"

params:
  env: production

  profileMode:
    enabled: true
    title: "Leonard James"
    subtitle: "Desenvolvedor Full-stack Jr • Golang • TypeScript"
    imageUrl: "/images/eu.jpeg"
    imageTitle: "Leonard James"

  mainSections:
    - posts
